num1=float(input("Ingresa un numero decimal para convertirlo en entero: "))
print(num1)
num1str=str(num1)
num1=int(num1)
print("El numero en formato texto: "+num1str)
print("El numero en formato entero"+num1)
print("************************************************")
print("Ahora pasame un numero para convertirlo en cadena y despues otro numero para sumarlos")
num2=str(input("Ingresa un numero decimal : "))
num3=float(input("Ingresa un numero decimal: "))
suma=num3+float(num2)
print(suma)